version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Dependabot] npm"
    labels:
      - "npm"
      - "dependencies"
      - "update"
    allow:
      - dependency-name: "react*"
      - dependency-name: "redux*"
